services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-weather}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-weather}
      POSTGRES_DB: ${POSTGRES_DB:-weather}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-weather} -d ${POSTGRES_DB:-weather}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Host `db`
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-weather}:${POSTGRES_PASSWORD:-weather}@db:5432/${POSTGRES_DB:-weather}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
